-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 16:55:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbnutrit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbnutrit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbnutrit` DEFAULT CHARACTER SET utf8 ;
USE `dbnutrit` ;

-- -----------------------------------------------------
-- Table `dbnutrit`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnutrit`.`pacientes` (
  `idpacientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidop` VARCHAR(50) NOT NULL,
  `apellidom` VARCHAR(50) NOT NULL,
  `genero` TINYINT NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(100) NULL,
  `telefono` VARCHAR(20) NULL,
  PRIMARY KEY (`idpacientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnutrit`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnutrit`.`registro` (
  `idregistro` INT NOT NULL AUTO_INCREMENT,
  `idpacientes` INT NOT NULL,
  `motivo` VARCHAR(200) NULL,
  `ocupacion` VARCHAR(45) NULL,
  `foto` VARCHAR(50) NULL,
  PRIMARY KEY (`idregistro`),
  INDEX `fk_registro_pacientes_idx` (`idpacientes` ASC),
  CONSTRAINT `fk_registro_pacientes`
    FOREIGN KEY (`idpacientes`)
    REFERENCES `dbnutrit`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnutrit`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnutrit`.`historial` (
  `idhistorial` INT NOT NULL AUTO_INCREMENT,
  `idpacientes` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `pa` INT NOT NULL,
  PRIMARY KEY (`idhistorial`),
  INDEX `fk_historial_pacientes_idx` (`idpacientes` ASC),
  CONSTRAINT `fk_historial_pacientes`
    FOREIGN KEY (`idpacientes`)
    REFERENCES `dbnutrit`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnutrit`.`dietas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnutrit`.`dietas` (
  `iddietas` INT NOT NULL AUTO_INCREMENT,
  `idpacientes` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddietas`),
  INDEX `fk_dietas_pacientes_idx` (`idpacientes` ASC),
  CONSTRAINT `fk_dietas_pacientes`
    FOREIGN KEY (`idpacientes`)
    REFERENCES `dbnutrit`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnutrit`.`alimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnutrit`.`alimentos` (
  `idalimentos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calorias` INT NOT NULL,
  PRIMARY KEY (`idalimentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnutrit`.`lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnutrit`.`lista` (
  `idlista` INT NOT NULL AUTO_INCREMENT,
  `idalimentos` INT NOT NULL,
  `iddietas` INT NOT NULL,
  PRIMARY KEY (`idlista`),
  INDEX `fk_alimentos_lista_idx` (`idalimentos` ASC),
  INDEX `fk_dietas_lista_idx` (`iddietas` ASC),
  CONSTRAINT `fk_alimentos_lista`
    FOREIGN KEY (`idalimentos`)
    REFERENCES `dbnutrit`.`alimentos` (`idalimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dietas_lista`
    FOREIGN KEY (`iddietas`)
    REFERENCES `dbnutrit`.`dietas` (`iddietas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
